# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='products.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproducts.proto\x12\x0bproducts.v1\"#\n\x11\x43lientRequestType\x12\x0e\n\x06vendor\x18\x01 \x01(\t\")\n\x12\x43lientResponseType\x12\x13\n\x0bproductType\x18\x01 \x01(\t\"<\n\x15\x43lientRequestProducts\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x13\n\x0bproductType\x18\x02 \x01(\t\"A\n\x16\x43lientResponseProducts\x12\'\n\x07product\x18\x01 \x01(\x0b\x32\x16.products.v1.ProdsPrep\"9\n\tProdsPrep\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08shortUrl\x18\x03 \x01(\t\"j\n\x1a\x41\x64minClientRequestProducts\x12\'\n\x07product\x18\x01 \x01(\x0b\x32\x16.products.v1.ProdsPrep\x12\x0e\n\x06vendor\x18\x02 \x01(\t\x12\x13\n\x0bproductType\x18\x03 \x01(\t\"\x1d\n\x0cProductCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\xa5\x02\n\x0eProductService\x12X\n\x15GetVendorProductTypes\x12\x1e.products.v1.ClientRequestType\x1a\x1f.products.v1.ClientResponseType\x12^\n\x11GetVendorProducts\x12\".products.v1.ClientRequestProducts\x1a#.products.v1.ClientResponseProducts0\x01\x12Y\n\x11SetVendorProducts\x12\'.products.v1.AdminClientRequestProducts\x1a\x19.products.v1.ProductCount(\x01\x62\x06proto3'
)




_CLIENTREQUESTTYPE = _descriptor.Descriptor(
  name='ClientRequestType',
  full_name='products.v1.ClientRequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor', full_name='products.v1.ClientRequestType.vendor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)


_CLIENTRESPONSETYPE = _descriptor.Descriptor(
  name='ClientResponseType',
  full_name='products.v1.ClientResponseType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='productType', full_name='products.v1.ClientResponseType.productType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=109,
)


_CLIENTREQUESTPRODUCTS = _descriptor.Descriptor(
  name='ClientRequestProducts',
  full_name='products.v1.ClientRequestProducts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor', full_name='products.v1.ClientRequestProducts.vendor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='productType', full_name='products.v1.ClientRequestProducts.productType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=171,
)


_CLIENTRESPONSEPRODUCTS = _descriptor.Descriptor(
  name='ClientResponseProducts',
  full_name='products.v1.ClientResponseProducts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='products.v1.ClientResponseProducts.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=238,
)


_PRODSPREP = _descriptor.Descriptor(
  name='ProdsPrep',
  full_name='products.v1.ProdsPrep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='products.v1.ProdsPrep.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='products.v1.ProdsPrep.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortUrl', full_name='products.v1.ProdsPrep.shortUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=297,
)


_ADMINCLIENTREQUESTPRODUCTS = _descriptor.Descriptor(
  name='AdminClientRequestProducts',
  full_name='products.v1.AdminClientRequestProducts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='products.v1.AdminClientRequestProducts.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='products.v1.AdminClientRequestProducts.vendor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='productType', full_name='products.v1.AdminClientRequestProducts.productType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=405,
)


_PRODUCTCOUNT = _descriptor.Descriptor(
  name='ProductCount',
  full_name='products.v1.ProductCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='products.v1.ProductCount.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=436,
)

_CLIENTRESPONSEPRODUCTS.fields_by_name['product'].message_type = _PRODSPREP
_ADMINCLIENTREQUESTPRODUCTS.fields_by_name['product'].message_type = _PRODSPREP
DESCRIPTOR.message_types_by_name['ClientRequestType'] = _CLIENTREQUESTTYPE
DESCRIPTOR.message_types_by_name['ClientResponseType'] = _CLIENTRESPONSETYPE
DESCRIPTOR.message_types_by_name['ClientRequestProducts'] = _CLIENTREQUESTPRODUCTS
DESCRIPTOR.message_types_by_name['ClientResponseProducts'] = _CLIENTRESPONSEPRODUCTS
DESCRIPTOR.message_types_by_name['ProdsPrep'] = _PRODSPREP
DESCRIPTOR.message_types_by_name['AdminClientRequestProducts'] = _ADMINCLIENTREQUESTPRODUCTS
DESCRIPTOR.message_types_by_name['ProductCount'] = _PRODUCTCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientRequestType = _reflection.GeneratedProtocolMessageType('ClientRequestType', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTTYPE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ClientRequestType)
  })
_sym_db.RegisterMessage(ClientRequestType)

ClientResponseType = _reflection.GeneratedProtocolMessageType('ClientResponseType', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSETYPE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ClientResponseType)
  })
_sym_db.RegisterMessage(ClientResponseType)

ClientRequestProducts = _reflection.GeneratedProtocolMessageType('ClientRequestProducts', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTPRODUCTS,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ClientRequestProducts)
  })
_sym_db.RegisterMessage(ClientRequestProducts)

ClientResponseProducts = _reflection.GeneratedProtocolMessageType('ClientResponseProducts', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSEPRODUCTS,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ClientResponseProducts)
  })
_sym_db.RegisterMessage(ClientResponseProducts)

ProdsPrep = _reflection.GeneratedProtocolMessageType('ProdsPrep', (_message.Message,), {
  'DESCRIPTOR' : _PRODSPREP,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ProdsPrep)
  })
_sym_db.RegisterMessage(ProdsPrep)

AdminClientRequestProducts = _reflection.GeneratedProtocolMessageType('AdminClientRequestProducts', (_message.Message,), {
  'DESCRIPTOR' : _ADMINCLIENTREQUESTPRODUCTS,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.AdminClientRequestProducts)
  })
_sym_db.RegisterMessage(AdminClientRequestProducts)

ProductCount = _reflection.GeneratedProtocolMessageType('ProductCount', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTCOUNT,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.v1.ProductCount)
  })
_sym_db.RegisterMessage(ProductCount)



_PRODUCTSERVICE = _descriptor.ServiceDescriptor(
  name='ProductService',
  full_name='products.v1.ProductService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=439,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVendorProductTypes',
    full_name='products.v1.ProductService.GetVendorProductTypes',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUESTTYPE,
    output_type=_CLIENTRESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetVendorProducts',
    full_name='products.v1.ProductService.GetVendorProducts',
    index=1,
    containing_service=None,
    input_type=_CLIENTREQUESTPRODUCTS,
    output_type=_CLIENTRESPONSEPRODUCTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetVendorProducts',
    full_name='products.v1.ProductService.SetVendorProducts',
    index=2,
    containing_service=None,
    input_type=_ADMINCLIENTREQUESTPRODUCTS,
    output_type=_PRODUCTCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTSERVICE)

DESCRIPTOR.services_by_name['ProductService'] = _PRODUCTSERVICE

# @@protoc_insertion_point(module_scope)
